version: "3.1"
services:
  app:
    image: node
    user: "node"
    working_dir: /home/node/app
    # environment:
    #   - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - "80:80"
    command: "npm start"
    restart: always